portal/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web'] ], function() {
    Route::get('/',         ['as' => 'auth.index',  'uses' => 'AuthController@index']);
    Route::get('login',     ['as' => 'auth.index',  'uses' => 'AuthController@index']);
    Route::post('login',    ['as' => 'auth.login',  'uses' => 'AuthController@login']);
    Route::get('logout',    ['as' => 'auth.logout', 'uses' => 'AuthController@logout']);
});

Route::group(['middleware' => ['web','auth','acl'] ], function() {
    /*
     * Dashboard
     */
    Route::get('dashboard/indexData', ['as' => 'dashboard.index.data', 'uses' => 'DashboardController@indexData']);
    Route::get('dashboard', ['as'=>'dashboard', 'uses'=>'DashboardController@index']);

    /*
     * Form preorder
     */
    Route::get('preorder/indexData', ['as' => 'preorder.index.data', 'uses' => 'PreorderController@indexData']);
    Route::get('preorder/checkout', ['as' => 'preorder.checkout', 'uses' => 'PreorderController@checkout']);
    Route::get('preorder/payment', ['as' => 'preorder.payment', 'uses' => 'PreorderController@payment']);
    Route::post('preorder/updateListPreorder', ['as' => 'preorder.update.list_preorder', 'uses'=>"PreorderController@updateListPreorder"]);
    Route::post('preorder/updatePreorder', ['as' => 'preorder.update.preorder', 'uses' => 'PreorderController@updatePreorder']);
    Route::post('preorder/deleteList', ['as' => 'preorder.delete.list', 'uses'=>"PreorderController@deleteList"]);
    Route::resource('preorder','PreorderController');

     /*
     * Trackorder
     */
    Route::get('trackorder/indexData', ['as' => 'trackorder.index.data', 'uses' => 'TrackorderController@indexData']);
    Route::put('trackorder/upload/{id}', ['as'=>'trackorder.upload', 'uses'=>'TrackorderController@uploadBukti']);
    Route::post('trackorder/upload/{id}', ['as'=>'trackorder.upload', 'uses'=>'TrackorderController@uploadBukti']);
    Route::post('trackorder/deleteAll/{id}', ['as'=>'trackorder.deleteAll', 'uses'=>'TrackorderController@deleteBuktiAll']);
    Route::get('trackorder/upload/{id}', ['as'=>'trackorder.upload', 'uses'=>'TrackorderController@upload']);
    Route::get('trackorder', ['as'=>'trackorder', 'uses'=>'TrackorderController@index']);
    Route::get('trackorder/{trackorder}', ['as'=>'trackorder.show', 'uses'=>'TrackorderController@show']);
    
     /*
     * Order
     */
    Route::get('order/indexData', ['as' => 'order.index.data', 'uses' => 'OrderController@indexData']);
    Route::resource('order','OrderController');
    
    /**
     * Saldo
     * **/
    Route::get('profile/saldo/indexData', ['as' => 'profile.saldo.data', 'uses' => 'MemberController@indexDataSaldo']);
    Route::get('profile/saldo', ['as' => 'profile.saldo', 'uses' => 'MemberController@saldo']);
    Route::resource('profile','MemberController');
    
     /*** Portal Promo ***/
    Route::get('portal_promo/indexData', [
        'as'=>'portal_promo.index.data', 'uses'=>'PortalPromoController@indexData'
    ]);
    Route::resource('portal_promo','PortalPromoController');
    
     /*
     * Notification
     */
    Route::get('notification/indexData', ['as' => 'notification.index.data', 'uses' => 'NotificationController@indexData']);
    Route::get('notification', ['as'=>'notification.index', 'uses'=>'NotificationController@index']);
    Route::get('notification/{id}', ['as'=>'notification.show', 'uses'=>'NotificationController@show']);
});

portal/app/Models/Member.php
<?php

namespace App\Models;

use App\Component\Model;
use Zain\Helper;
use DB;

/**
 * @property integer $id 
 * @property string $nama 
 * @property string $alamat 
 * @property string $telepon 
 * @property string $tgl_lahir 
 * @property string $tempat_lahir
 * @property integer $jenis_id
 * @property string $no_id 
 * @property integer $user_id 
 * @property integer $jenis_member 
 * @property double $saldo 
 * 
 * @property User $user 
 * **/

class Member extends Model
{
    const JENIS_ID_KP = 5;
    const JENIS_ID_KTP = 10;
    const JENIS_ID_SIM = 15;
    
    const JENIS_MEMBER = 10;
    const JENIS_DEALER = 20;

    protected $table = 'member';
    protected $fillable = ['nama','alamat','telepon','tgl_lahir','tempat_lahir','jenis_id','no_id','kcp_id','jenis_member','saldo'];
    
    protected function rules() {
        return [
            'nama'=>['required'],
            'jenis_id'=>['required'],
            'no_id'=>['required'],
            'telepon'=>['required'],
            'alamat'=>['required'],
        ];
    }
    
    protected static function attributeNames() {
        return [
            'nama'=>'Nama Lengkap',
            'alamat'=>'Alamat Lengkap',
            'telepon'=>'Telepon',
            'tgl_lahir'=>'Tanggal Lahir',
            'tempat_lahir'=>'Tempat Lahir',
            'member_card'=>'Kartu Member Detail',
            'jenis_id'=>'Jenis Identitas',
            'no_id'=>'No Identitas',
            'user_id'=>'User',
        ];
    }
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public function fill(array $attributes)
    {
        if(isset($attributes['tgl_lahir'])){
            $attributes['tgl_lahir'] = Helper::formatDate($attributes['tgl_lahir'], Helper::FORMAT_DATE_EN_SHORT);
        }
        
        return parent::fill($attributes);
    }
    
    public function memberCards(){
        return $this->hasOne(MemberCard::class);
    }
    
    public function memberSaldo()
    {
        return $this->hasMany(MemberSaldo::class);
    }

    public function validateWithMemberCard(array $input){
        $res = $this->validate();
        $errors = $this->errors;
        
        $memberCard = new MemberCard();
        $memberCard->fill($input);
        
        if(!$memberCard->validate()){
            $errors = array_merge($errors, $memberCard->errors);
            $res = false;
        }
        
        $this->errors = $errors;
        
        return $res;
    }
    
    public function saveWithMemberCard(array $input)
    {
        DB::beginTransaction();
        
        $res = $this->validate();
        $errors = $this->errors;
        
        if($res && $this->save() && $this->saveUser($input)){
            $memberCard = (count($this->memberCards) > 0) ? $this->memberCards : new MemberCard();
            $memberCard->fill($input);
            $memberCard->member_id = $this->id;
            
            $res = $memberCard->validate();
            
            if(!($res && $memberCard->save())){
                $res = false;
                $errors = array_merge($errors, $memberCard->errors);
            }
        }else{
            $res = false;
            $errors = array_merge($errors, $this->errors);
        }
        
        $res ? DB::commit() : DB::rollback();
        
        $this->errors = $errors;
        
        return $res;
    }
    
    public function saveUser(array $input)
    {
        if($this->jenis_member == self::JENIS_DEALER){
            $user = new User();
            if($this->user){
                $user  = $this->user;
            }
            
            $user->nama     = $this->nama;
            $user->username = $input["username"];
            $user->level    = User::LEVEL_MEMBER_DEALER;
            $user->status   = User::STATUS_AKTIF;
            $user->password = $input["password"];
            
            if($user->validate()){
                $user->save();
                
                $this->user_id = $user->id;
                $this->save();
                return TRUE;
            }else{
                $this->errors = $user->errors;
                return FALSE;
            }
        }else{
            if($this->user){
                $this->user_id = null;
                $this->user->delete();
            }
            
            return TRUE;
        }
    }

    public function delete()
    {
        DB::beginTransaction();
        $res = true;
        
        $res = $this->memberCards->delete();
        
        if($res){
            $res = parent::delete();
        }
                
        $res ? DB::commit() : DB::rollback();
        
        return $res;
    }
    
    public static function getJenisIDList() 
    {
        return Lookup::items(Lookup::JENIS_ID_MEMBER);
    }
    
    public function getJenisId()
    {
        return Lookup::item(Lookup::JENIS_ID_MEMBER, $this->jenis_id);
    }
    
    public static function getJenisMemberList() 
    {
        return Lookup::items(Lookup::JENIS_MEMBER);
    }
    
    public static function getJenisMember() 
    {
        return Lookup::item(Lookup::JENIS_MEMBER, $this->jenis_member);
    }
    
    public function calculateSaldo(){
        $member_card_id = $this->memberCards->id;
        
        $q1 = Preorder::select(\DB::raw("SUM(preorder.saldo) as saldo_total"))
                ->where('preorder.member_card_id',$member_card_id)
                ->whereNull("penjualan_id");
        
        $q3 = Penjualan::select(\DB::raw("SUM(saldo_member) as saldo_total"))
                ->where('member_card_id',$member_card_id)
                ->groupBy('member_card_id');
        
        $saldo_min = $q1->unionAll($q3)->get()->sum("saldo_total");
        $saldo_min = is_numeric($saldo_min) ? $saldo_min : 0;
        
        
        $saldo_add = Preorder::where('preorder.member_card_id',$member_card_id)
                ->where('status_order',  Preorder::ORDER_DIBATALKAN)
                ->sum("preorder.saldo");
        $saldo_add = is_numeric($saldo_add) ? $saldo_add : 0;
        
        $member_saldo = $this->memberSaldo()->sum('saldo');
        
        $saldo = $member_saldo + $saldo_add - $saldo_min; 
        
        $this->saldo = $saldo;
        
        return $this->save();
    }
}

portal/app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use View;
use App\Models\Member;
use App\Models\MemberSaldo;
use Auth;
use Bllim\Datatables\Datatables;
use Karsa\Helper;
use DB;
use App\Models\Preorder;

class MemberController extends Controller
{
    public function edit($id)
    {
        $model = Member::find($id);
        $user = $model->user;
        if($user){
            $model->username = $user->username;
            $model->password = $user->password;
        }
        $modelCard = $model->memberCards;
        return View::make('member.edit',  compact('model','modelCard'));
    }

    public function update(Request $request, $id)
    {
        $input = $request->all();
        $model = Member::find($id);
        $model->fill($input);
        
        if($model->validateWithMemberCard($input) && $model->saveWithMemberCard($input)){
            return $model->id;
        }
        
        return '<div>'.  implode('<div></div>', $model->errors).'</div>';
    }
    
    public function saldo()
    {
        Auth::user()->getMemberCard()->member->calculateSaldo();
        return \View::make('member.saldo');
    }
    
    public function indexDataSaldo(Request $request)
    {
        $q1 = DB::table('member_saldo as ms')
                ->select(DB::raw(" ms.tanggal, ms.saldo, ms.keterangan, 'Debit' as tipe, ms.created_at"))
                ->where("ms.member_id",  Auth::user()->getMemberCard()->member->id);
        
        $q2 = DB::table('penjualan as p')
                ->select(DB::raw("p.tgl_penjualan as tanggal, p.saldo_member as saldo, CONCAT('Pembelian : ', p.no_referensi) as keterangan, 'Kredit' as tipe, p.created_at"))
                ->where("member_card_id",  Auth::user()->getMemberCard()->id)
                ->where("p.saldo_member", ">",  0);
        
        $q3 = DB::table("preorder")
                ->select(DB::raw("tanggal, saldo, CONCAT('Preorder : ', no_order) as keterangan,'Kredit' as tipe, created_at"))
                ->where("member_card_id",Auth::user()->getMemberCard()->id)
                ->whereNull("penjualan_id")
                ->where("saldo", ">",  0);
        
        $q4 = DB::table("preorder")
                ->select(DB::raw("tanggal, saldo, CONCAT('Void Preorder : ', no_order) as keterangan,'Debit' as tipe, created_at"))
                ->where("member_card_id",Auth::user()->getMemberCard()->id)
                ->where("status_order",Preorder::ORDER_DIBATALKAN)
                ->where("saldo", ">",  0);
        
        if($request->get("tanggal")){
            $tanggal = date("Y-m-d",strtotime($request->get("tanggal")));
            $q1->where("tanggal",$tanggal);
            $q2->where("tgl_penjualan",$tanggal);
        }

        if($request->get("search")){
            $search = $request->get("search");

            $q1->where(function($q) use ($search) {
                $q->where("saldo","=",$search)
                    ->orWhere("keterangan","like","%". $search ."%");
            });

            $q2->where(function($q) use ($search) {
                $q->where("saldo_member","=",$search)
                    ->orWhere("keterangan","like","%". $search ."%");
            });
        }

        $query = $q1->unionAll($q2)->unionAll($q3)->unionAll($q4)->orderBy("created_at","ASC");
        
        $result= [];
        $saldo = 0;
        $rs = $query->get()->toArray();
        $i = count($rs) - 1;
        
        foreach ($rs as $k => $v) {
            $v->tanggal = Helper::formatDate($v->tanggal, Helper::FORMAT_DATE_ID_LONG);
            $v->nominal = Helper::idNumber($v->saldo);
            
            if($v->tipe == "Debit"){
                $v->tipe = '<span class="block" style="background:green;font-size:10px;">'.$v->tipe.'</span>';
                $saldo += $v->saldo;
            }elseif ($v->tipe == "Kredit") {
                $v->tipe = '<span class="block" style="background: red;font-size:10px;">'.$v->tipe.'</span>';
                $saldo -= $v->saldo;
            }
            $v->sisa = Helper::idNumber($saldo);
            $result[] = $v;
        }
        
        krsort($result);
        $data = array_values($result);
        
        $json_data = array(
                    "recordsTotal"    => intval($data),  
                    "recordsFiltered" => intval($data), 
                    "data"            => $data   
        );
        return response()->json($json_data);
    }
}

portal/resources/views/member/_form.blade.php
<?php

use App\Models\Member;
use App\Models\MemberCard;
use App\Models\User;
use Karsa\Helper;

/* @var $model Member */

?>
<div class="row">
    <div class="col-md-5">
        <div class="panel panel-default">
            <div class="panel-heading">Data Member</div>
            <div class="panel-body">
                <div class="row">                        
                    <div class="form-group col-lg-5">
                        <?= Form::label('jenis_id', Member::getAttributeName('jenis_id')) ?>
                        <dd><?= $model->getJenisId() ?></dd>
                    </div>
                    <div class="form-group col-lg-5">
                        <?= Form::label('no_id', Member::getAttributeName('no_id')) ?>
                        <dd><?= $model->no_id ?></dd>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">                       
                        <p class="ket">Isikan data profile sesuai kartu identitas</p>                        
                    </div>
                </div>
                <div class="row">                        
                    <div class="form-group col-lg-10">
                        <?= Form::label('nama', Member::getAttributeName('nama')) ?>
                        <dd><?= $model->nama ?></dd>
                    </div>
                </div>
                <div class="row">                        
                    <div class="form-group col-lg-5">
                        <?= Form::label('tempat_lahir', Member::getAttributeName('tempat_lahir')) ?>
                        <?= Form::text('tempat_lahir', null,['class'=>'form-control','placeholder'=>'e.x : Surabaya']) ?>
                    </div>
                    <div class="form-group col-lg-5">
                        <?= Form::label('tgl_lahir', Member::getAttributeName('tgl_lahir')) ?>
                        <div class="input-group">
                            <?= Form::text('tgl_lahir', $model->tgl_lahir ? 
                                    Helper::formatDate($model->tgl_lahir, Helper::FORMAT_DATE_ID_SHORT) : null,
                                    ['class'=>'form-control datepicker','placeholder'=>'e.x : 21-01-2017']) ?>
                            <span class="input-group-addon">
                                <i class="fa fa-calendar bigger-110"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-5">
                        <?= Form::label('telepon', Member::getAttributeName('telepon')) ?>
                        <?= Form::text('telepon',null,['class'=>'form-control','placeholder'=>'e.x : 081220923580']) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-10">
                        <?= Form::label('alamat', Member::getAttributeName('alamat')) ?>
                        <?= Form::text('alamat',null,['class'=>'form-control','placeholder'=>'e.x : Jalan Soekarno Hatta D505 Malang']) ?>
                    </div>
                </div>
            </div>
        </div>            
    </div>

    <div class="col-md-7">
        <div class="panel panel-primary">
            <div class="panel-heading">Data Kartu Member</div>
            <div class="panel-body" style="background: #f5f5f5;">
                <div class="row">
                    <div class="form-group col-lg-3">
                        <?= Form::label('no_kartu', MemberCard::getAttributeName('no_kartu')) ?>
                        <dd><?= $modelCard->no_kartu ?></dd>
                    </div>
                    <div class="form-group col-lg-3">
                        <?= Form::label('jenis', MemberCard::getAttributeName('jenis')) ?>
                        <dd><?= $modelCard->getJenis() ?></dd>
                    </div>                
                    <div class="form-group col-lg-3">
                        <?= Form::label('jumlah_tempo', MemberCard::getAttributeName('jumlah_tempo')) ?>
                        <dd><?= $modelCard->jumlah_tempo ?></dd>
                    </div>
                    <div class="form-group col-lg-3">
                        <?= Form::label('max_piutang', MemberCard::getAttributeName('max_piutang')) ?>
                        <dd><?= Helper::idNumber($modelCard->max_piutang) ?></dd>
                    </div>
                </div>
            </div>
        </div>                               
    </div>
    
    <div class="col-md-7" id="form-user">
        <div class="panel panel-primary">
            <div class="panel-heading">Data User</div>
            <div class="panel-body" style="background: #f5f5f5;">
                <div class="row">
                    <div class="form-group col-lg-6">
                        <?= Form::label('username', User::getAttributeName('username')) ?>
                        <?= Form::text('username',null,['class'=>'form-control','placeholder'=>'e.x : andri']) ?>
                    </div>
                    <div class="form-group col-lg-6">
                        <?= Form::label('password', User::getAttributeName('password')) ?>
                        <div class="input-group">
                            <?= Form::password('password', ['class'=>'form-control']) ?>
                            <span class="input-group-addon clickable">
                                <i class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>                               
    </div>
</div>

<div class="form-group">
    <button type="submit" class="btn btn-success">
        <i class="fa fa-save"></i>
        Simpan
    </button>
    <a href="<?=route('profile.index')?>" class="btn btn-primary">
        <i class="ace-icon fa fa-arrow-left"></i>
        Kembali
    </a>
</div>

@section('js-include')
<script type="text/javascript" src="<?= asset('vendor/') ?>/utils/jquery.format-number.js"></script>
<script type="text/javascript" src="<?= asset('vendor/') ?>/utils/jquery.enter-next.js"></script>
<script type="text/javascript" src="<?= asset('vendor/') ?>/chosen/chosen.jquery.min.js"></script>
@endsection 

@section('css-include')
<link rel="stylesheet" href="<?= asset('vendor/') ?>/chosen/chosen.min.css" />
@endsection 

@section('js-inline')
//<script type="text/javascript">
$(function(){
    ajaxFormGritter.bind('mainForm',{onSuccess:function(data){
        document.location = document.location;
    }});

    $('.datepicker').datepicker({
        format: 'dd-mm-yyyy',
        autoclose: true,
        todayHighlight: true
    });
    
    $('.chosen-select').chosen({allow_single_deselect:true}); 
    
    $('[type=password]').next().mousedown(function(){ $(this).prev().attr('type', 'text'); });
    $('[type=password]').next().mouseup(function(){ $(this).prev().attr('type', 'password'); });
    
    $('.format-number').formatNumber();

    $('input:not([disabled=disabled]),select,[type=submit]').enterNext();
    
    $('[type=password]').next().mousedown(function(){ $(this).prev().attr('type', 'text'); });
    $('[type=password]').next().mouseup(function(){ $(this).prev().attr('type', 'password'); });
});
@endsection

portal/resources/views/member/edit.blade.php
@extends('layout/default')

@section('title')
Member
@endsection

@section('breadcrumb')
<li>
    <a href="<?= route('profile.index')?>">Member</a>
</li>
<li>
    Edit
</li>
@endsection

@section('content-header')
Member
<small>
    <i class="ace-icon fa fa-angle-double-right"></i>
    Edit
</small>
@endsection

@section('content')
<div class="content-wrapper">    
    <!-- Main content -->
    <section class="content">
    <div class="row">
        <div class="col-md-12">
            <?= Form::model($model, ['route' => ['profile.update', $model->id], 'id'=>'mainForm', 'method'=>'PUT']) ?>
            @include('member/_form')
            <?= Form::close() ?>
        </div>
    </div>
    </section>
</div>
@endsection

portal/resources/views/member/saldo.blade.php
<?php
use Karsa\Helper;
use App\Models\MemberSaldo;
?>

@extends('layout.default')

@section('title')
Saldo
@endsection

@section('content')
<div class="content-wrapper">    
    <!-- Main content -->
    <section class="content">
      <div class="row">
        
        <div class="col-md-3 col-xs-12 col-sm-12 filter-top" style="margin-bottom: 15px;">               
          <form class="form-inline">
            <div class="form-group">              
              <div class="input-group">                  
                <?= Form::text('search',"",['class'=>'form-control',"placeholder"=>"Keyword"]) ?>                
                <div class="input-group-addon search"><span class="fa fa-search"></span></div>
              </div>
            </div>              
          </form>         
        </div>

        <div class="col-md-3 col-xs-12 col-sm-12 filter-top" style="margin-bottom: 15px;">
            <div class="form-group">
                <div class="input-group date">
                    <input type="text" class="form-control pull-right datepicker" placeholder="<?= MemberSaldo::getAttributeName('tanggal') ?>" id="tanggal">
                    <div class="input-group-addon">
                    	<i class="fa fa-calendar"></i>
                    </div>
                </div>                
            </div>                                
        </div>

        <div class="col-md-3 col-xs-12 col-sm-12 filter-top" style="margin-bottom: 15px;">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <a href="#" class="btn btn-block btn-info" title="Saldo" data-toggle="tooltip">
                    Rp <?= Helper::idNumber(Auth::user()->getMemberCard()->member->saldo) ?>
                </a>
            </div>

            <div class="col-md-6 col-sm-6 col-xs-6">
                <a href="#" class="btn btn-block btn-danger" title="Piutang" data-toggle="tooltip">
                    Rp <?= Helper::idNumber(Auth::user()->getMemberCard()->getTotalPiutang()) ?>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header">
                <h3 class="box-title">History Add Saldo</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
              <table class="table table-hover" id="mainTable">
                <thead>
                    <th><?= MemberSaldo::getAttributeName('tanggal') ?></th>
                    <th><?= MemberSaldo::getAttributeName('keterangan') ?></th>
                    <th><?= MemberSaldo::getAttributeName('tipe') ?></th>
                    <th>Nominal </th>
                    <th><?= MemberSaldo::getAttributeName('saldo') ?> </th>
                </thead>
              </table>
            </div>
          </div>
        </div>        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('js-include')
<script type="text/javascript" src="<?= asset('vendor/') ?>/jquery.datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?= asset('vendor/') ?>/jquery.datatables/jquery.dataTables.bootstrap.min.js"></script>
@endsection

@section('js-inline')
//<script type="text/javascript">
$(function(){
    mainTable = $('#mainTable').dataTable({
        "aoColumns": [ 
            { "data": "tanggal","bSortable": false },
            { "data": "keterangan","bSortable": false },
            { "data": "tipe","bSortable": false },
            { "data": "nominal","bSortable": false },
            { "data": "sisa","bSortable": false }
        ],
        "stateSave": true,
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?= route('profile.saldo.data')?>",
        "sServerMethod": "GET",
//        "aaSorting": [[ 0, "asc" ]],
        "bLengthChange": false,
        "bFilter": false,
        "iDisplayRow": 25,
//        "iDisplayLength": 50,
//        "pageLength" : 25,
        "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
        "fnServerParams": function ( aoData ) {
            aoData.push( { "name": "_token", "value": '<?=  csrf_token() ?>' } );
            aoData.push({ "name": "search", "value": $('[name=search]').val() });
            aoData.push({ "name": "tanggal", "value": $('#tanggal').val() });
        }
    });
    
    $('.datepicker').datepicker({
        format: 'dd-mm-yyyy',
        autoclose: true,
        todayHighlight: true
    });
    
    $('[name=search]').keyup(function(){
        mainTable.fnDraw(false);
    });
    
    $('#tanggal').change(function(){
        mainTable.fnDraw(false);
    });
})
@endsection