portal/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web'] ], function() {
    Route::get('/',         ['as' => 'auth.index',  'uses' => 'AuthController@index']);
    Route::get('login',     ['as' => 'auth.index',  'uses' => 'AuthController@index']);
    Route::post('login',    ['as' => 'auth.login',  'uses' => 'AuthController@login']);
    Route::get('logout',    ['as' => 'auth.logout', 'uses' => 'AuthController@logout']);
});

Route::group(['middleware' => ['web','auth','acl'] ], function() {
    /*
     * Dashboard
     */
    Route::get('dashboard/indexData', ['as' => 'dashboard.index.data', 'uses' => 'DashboardController@indexData']);
    Route::get('dashboard', ['as'=>'dashboard', 'uses'=>'DashboardController@index']);

    /*
     * Form preorder
     */
    Route::get('preorder/indexData', ['as' => 'preorder.index.data', 'uses' => 'PreorderController@indexData']);
    Route::get('preorder/checkout', ['as' => 'preorder.checkout', 'uses' => 'PreorderController@checkout']);
    Route::get('preorder/payment', ['as' => 'preorder.payment', 'uses' => 'PreorderController@payment']);
    Route::post('preorder/updateListPreorder', ['as' => 'preorder.update.list_preorder', 'uses'=>"PreorderController@updateListPreorder"]);
    Route::post('preorder/updatePreorder', ['as' => 'preorder.update.preorder', 'uses' => 'PreorderController@updatePreorder']);
    Route::post('preorder/deleteList', ['as' => 'preorder.delete.list', 'uses'=>"PreorderController@deleteList"]);
    Route::resource('preorder','PreorderController');

     /*
     * Trackorder
     */
    Route::get('trackorder/indexData', ['as' => 'trackorder.index.data', 'uses' => 'TrackorderController@indexData']);
    Route::put('trackorder/upload/{id}', ['as'=>'trackorder.upload', 'uses'=>'TrackorderController@uploadBukti']);
    Route::post('trackorder/upload/{id}', ['as'=>'trackorder.upload', 'uses'=>'TrackorderController@uploadBukti']);
    Route::post('trackorder/deleteAll/{id}', ['as'=>'trackorder.deleteAll', 'uses'=>'TrackorderController@deleteBuktiAll']);
    Route::get('trackorder/upload/{id}', ['as'=>'trackorder.upload', 'uses'=>'TrackorderController@upload']);
    Route::get('trackorder', ['as'=>'trackorder', 'uses'=>'TrackorderController@index']);
    Route::get('trackorder/{trackorder}', ['as'=>'trackorder.show', 'uses'=>'TrackorderController@show']);
    
     /*
     * Order
     */
    Route::get('order/indexData', ['as' => 'order.index.data', 'uses' => 'OrderController@indexData']);
    Route::resource('order','OrderController');
    
    /**
     * Saldo
     * **/
    Route::get('profile/saldo/indexData', ['as' => 'profile.saldo.data', 'uses' => 'MemberController@indexDataSaldo']);
    Route::get('profile/saldo', ['as' => 'profile.saldo', 'uses' => 'MemberController@saldo']);
    Route::resource('profile','MemberController');
    
     /*** Portal Promo ***/
    Route::get('portal_promo/indexData', [
        'as'=>'portal_promo.index.data', 'uses'=>'PortalPromoController@indexData'
    ]);
    Route::resource('portal_promo','PortalPromoController');
    
     /*
     * Notification
     */
    Route::get('notification/indexData', ['as' => 'notification.index.data', 'uses' => 'NotificationController@indexData']);
    Route::get('notification', ['as'=>'notification.index', 'uses'=>'NotificationController@index']);
    Route::get('notification/{id}', ['as'=>'notification.show', 'uses'=>'NotificationController@show']);
});

portal/resources/views/layout/403.blade.php
@extends('layout/default')

@section('title')
403 Not Authorized
@endsection

@section('breadcrumb')
<li>
    Error
</li>
<li>
    403 Not Authorized
</li>
@endsection

@section('content-header')
403
<small>
    <i class="ace-icon fa fa-angle-double-right"></i>
    Not Authorized
</small>
@endsection

@section('content')
<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="error-container">
            <div class="well">
                <h1 class="grey lighter smaller">
                    <span class="blue bigger-125">
                        <i class="ace-icon fa fa-lock"></i>
                        403
                    </span>
                    Not Authorized
                </h1>

                <hr>
                <h3 class="lighter smaller">Maaf anda tidak memiliki hak untuk mengakses halaman ini!</h3>

                <hr>
                <div class="space"></div>

                <div class="center">
                    <a class="btn btn-grey" href="javascript:history.back()">
                        <i class="ace-icon fa fa-arrow-left"></i>
                        Kembali
                    </a>

                    <a class="btn btn-primary" href="{{route('dashboard')}}">
                        <i class="ace-icon fa fa-tachometer"></i>
                        Dashboard
                    </a>
                </div>
            </div>
        </div>

        <!-- PAGE CONTENT ENDS -->
    </div><!-- /.col -->
</div>
@endsection

portal/resources/views/layout/404.blade.php
@extends('layout/default')

@section('title')
404 Not Found
@endsection

@section('breadcrumb')
<li>
    Error
</li>
<li>
    404 Not Found
</li>
@endsection

@section('content-header')
404
<small>
    <i class="ace-icon fa fa-angle-double-right"></i>
    Not Found
</small>
@endsection

@section('content')
<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <div class="error-container">
            <div class="well">
                <h1 class="grey lighter smaller">
                    <span class="blue bigger-125">
                        <i class="ace-icon fa fa-sitemap"></i>
                        404
                    </span>
                    Not Found
                </h1>

                <hr>
                <h3 class="lighter smaller">Maaf halaman yang anda cari tidak dapat ditemukan!</h3>

                <hr>
                <div class="space"></div>

                <div class="center">
                    <a class="btn btn-grey" href="javascript:history.back()">
                        <i class="ace-icon fa fa-arrow-left"></i>
                        Kembali
                    </a>

                    <a class="btn btn-primary" href="{{route('dashboard')}}">
                        <i class="ace-icon fa fa-tachometer"></i>
                        Dashboard
                    </a>
                </div>
            </div>
        </div>

        <!-- PAGE CONTENT ENDS -->
    </div><!-- /.col -->
</div>
@endsection

portal/resources/views/layout/default.blade.php
<?php
use Karsa\Notification;
use App\Models\Notifications;
?>

<!DOCTYPE html>
<html>
<head>
    <title><?= Config::get('my.app_name_1') ?> - @yield('title')</title>
    <link rel="icon" type="image/png" href="<?= asset('vendor/') ?>/favicon.png">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/jquery.gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/jquery.gritter/css/jquery.gritter-add.css" />		
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/dataTables.bootstrap.css">	
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/bootstrap-toggle/bootstrap-toggle.min.css">	
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/iCheck/all.css">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/datepicker/datepicker3.css">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/AdminLTE.min.css">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/_all-skins.min.css">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/style.css">
    
    @yield('css-include')
    <style type="text/css">@yield('css-inline')</style>
</head>
<body class="hold-transition skin-blue sidebar-mini">
	<div class="wrapper">
		<header class="main-header">
		    <!-- Logo -->
		    <img src="<?= asset('vendor/') ?>/assets/images/logo.jpeg" class="logo">
		    <!-- Header Navbar: style can be found in header.less -->
		    <nav class="navbar navbar-static-top">
		      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </a>      
		      <div class="navbar-custom-menu">
		        <ul class="nav navbar-nav">
		          <!-- User Account: style can be found in dropdown.less -->
		          <li class="dropdown user user-menu">
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		              <span class="hidden-xs">Halo, <?= ucwords(Auth::user()->nama) ?></span>
		              <img src="<?= asset('vendor/') ?>/assets/images/foto.jpg" class="user-image" alt="User Image">
		            </a>            
		          </li>

		          <!-- Notifications: style can be found in dropdown.less -->
                    <?php
                        $notif = Notifications::getNotifications([
                            'is_read'   => Notifications::IS_NOT_READ,
                            'to'        => Auth::user()->id
                        ]);
                    ?>
		          <li class="dropdown notifications-menu">
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		              <i class="fa fa-bell-o"></i>
                      <span class="label label-warning"><?= count($notif) ?></span>
		            </a>
		            <ul class="dropdown-menu">
                        <li class="header">Anda memiliki <?= count($notif) ?> notifikasi</li>
		              <li>
		                <!-- inner menu: contains the actual data -->
		                <ul class="menu">
                            <?php foreach ($notif as $n) : ?>
                            <li>
                                <a href="<?= route('notification.show',$n['id']) ?>">
                                    <i class="fa fa-users text-aqua"></i> <?= $n['message'] ?>
                                </a>
                            </li>
                            <?php endforeach; ?>
		                </ul>
		              </li>
                      <li class="footer"><a href="<?= route('notification.index') ?>">View all</a></li>
		            </ul>
		          </li>

		          <!-- Menu -->
		          <li>
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i></a>
		            <ul class="dropdown-menu">
                        <li class="footer"><a href="<?= route('profile.edit',Auth::user()->getMemberCard()->member->id) ?>"><font color="#777">Edit Porfile</font></a></li>
                      <li class="footer"><a href="<?= route('auth.logout') ?>"><font color="#777">Logout</font></a></li>
		            </ul>
		          </li>
		        </ul>
		      </div>
		    </nav>
		</header>
		<aside class="main-sidebar">
		    <!-- sidebar: style can be found in sidebar.less -->
		    <section class="sidebar">
		      <!-- sidebar menu: : style can be found in sidebar.less -->
		      <ul class="sidebar-menu">     
		      	@if(Auth::user()->hasAbility('dashboard'))  
		        <li class="treeview">
		          <a href="<?= route('dashboard') ?>">
		            <i class="fa fa-home"></i><br> <span>Dashboard</span>            
		          </a>          
		        </li>     
		        @endif
		        @if(Auth::user()->hasAbility('order'))                                                                   
		        <li class="treeview">
		          <a href="<?= route('preorder.create') ?>">
		            <i class="fa fa-shopping-cart"></i><br> <span>Order</span>            
		          </a>          
		        </li>
		        @endif
		        @if(Auth::user()->hasAbility('trackorder'))
		        <li class="treeview">
		          <a href="<?= route('trackorder') ?>">
		            <i class="fa fa-compass"></i><br> <span>Track Order</span>            
		          </a>          
		        </li>
		        @endif
                @if(Auth::user()->hasAbility('order'))
		        <li class="treeview">
		          <a href="<?= route('order.index') ?>">
		            <i class="fa fa-shopping-basket"></i><br> <span>Histori Order</span>            
		          </a>          
		        </li>
		        @endif
                @if(Auth::user()->hasAbility('profile.saldo'))
		        <li class="treeview">
		          <a href="<?= route('profile.saldo') ?>">
		            <i class="fa fa-money"></i><br> <span>Saldo</span>
		          </a>          
		        </li>
		        @endif
		        <li class="treeview">
                    <a href="<?= route('portal_promo.index') ?>">
		            <i class="fa fa-percent"></i><br> <span>Promo</span>            
		          </a>          
		        </li>
		      </ul>
		    </section>
		    <!-- /.sidebar -->
		</aside>
		
		@yield('content')
		
	</div>


	<script type="text/javascript" src="<?= asset('vendor/') ?>/assets/js/jquery.min.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/assets/js/bootstrap.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/input-mask/jquery.inputmask.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/input-mask/jquery.inputmask.date.extensions.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/input-mask/jquery.inputmask.extensions.js"></script>
    <script src="<?= asset('vendor/') ?>/jquery.gritter/js/jquery.gritter.min.js" type="text/javascript"></script>
    <script src="<?= asset('vendor/') ?>/jquery.gritter/js/jquery.gritter-add.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/iCheck/icheck.min.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/bootstrap-toggle/bootstrap-toggle.js"></script>
    <script type="text/javascript" src="<?= asset('vendor/') ?>/slimScroll/jquery.slimscroll.min.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/fastclick/fastclick.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/datepicker/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/assets/js/app.min.js"></script>
	<script type="text/javascript" src="<?= asset('vendor/') ?>/assets/js/demo.js"></script>
        
    <!-- inline scripts related to this page -->
    @yield('js-include')
    <script type="text/javascript">
        @yield('js-inline')
        $(function () {
            <?= Notification::showGritter() ?>
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>

portal/resources/views/layout/login.blade.php
<?php
use Karsa\Notification;
?>
<!DOCTYPE html>
<html>
<head>
	<title><?= Config::get('my.app_name') ?> - Login</title>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/assets/css/style.css">
    <link rel="icon" type="image/png" href="<?= asset('vendor/') ?>/favicon.png">
    <link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/jquery.gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="<?= asset('vendor/') ?>/jquery.gritter/css/jquery.gritter-add.css" />
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4 login">
				<div class="col-md-12">
					<img src="<?= asset('vendor/') ?>/assets/images/logo.jpeg">
				</div>		
				<div class="col-md-12 form-login">
					<span class="label-ket">Silahkan Login ke Akun anda</span>
					<br>
                    <?= Form::open(['route'=>'auth.login','method'=>'POST','id'=>'mainForm']) ?>
                    <?= csrf_field() ?>
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                    <input type="submit" name="login" value="Login" class="btn btn-primary">
                    <?= Form::close() ?>
				</div>		
			</div>
			<div class="col-md-8">
				<img src="<?= asset('vendor/') ?>/assets/images/loginimage.jpg" class="login-logo">
			</div>
		</div>
	</div>
    
    <script type="text/javascript" src="<?= asset('vendor/') ?>/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?= asset('vendor/') ?>/assets/js/bootstrap.js"></script>
    <script src="<?= asset('vendor/') ?>/jquery.gritter/js/jquery.gritter.min.js" type="text/javascript"></script>
    <script src="<?= asset('vendor/') ?>/jquery.gritter/js/jquery.gritter-add.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            ajaxFormGritter.bind('mainForm',{
                onSuccess:function(){
                    window.location = "<?= Redirect::intended('dashboard')->getTargetUrl() ?>";
                },
                _text : {
                    process: 'Validasi',
                    done: 'Login Berhasil',
                    error: 'Harap tunggu proses ini selesai...'
                }
            });
            <?= Notification::showGritter() ?>
        });
    </script>
</body>
</html>